server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ups_store
    username: root
    password: Damian@John07

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true


stripe:
  secret:
    key: YOUR_STRIPE_SECRET_KEY